version: "1"
project_name: MVP
project_description: "Prompt2Dataset - Multi-Service Orchestration"

services:
  # Database Layer
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: app_db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # LLM Services
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      OLLAMA_HOST: 0.0.0.0:11434
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ollama_data:/root/.ollama

  # Scraping/Parsing
  camoufox:
    image: camoufox/camoufox:latest
    ports:
      - "3000:3000"
    environment:
      HEADLESS: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  html-parser:
    build:
      context: ./services/html-parser
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      PORT: 5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - postgres

  # Search
  searxng:
    image: searxng/searxng:latest
    ports:
      - "8888:8888"
    environment:
      BASE_URL: https://search.${DOMAIN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Orchestration
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_HOST: postgres
      DB_NAME: n8n
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      N8N_SECURE_COOKIE: "false"
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5678/rest/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Agents
  extraction-agent:
    build:
      context: ./services/extraction-agent
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      LOG_LEVEL: info
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: app_db
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      HTML_PARSER_URL: http://html-parser:5000
    depends_on:
      - postgres
      - html-parser
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  vision-agent:
    build:
      context: ./services/vision-agent
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      PORT: 8002
      OLLAMA_URL: http://ollama:11434
      LOG_LEVEL: info
    depends_on:
      - ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  orchestrator-agent:
    build:
      context: ./services/orchestrator-agent
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      PORT: 8003
      LOG_LEVEL: info
      EXTRACTION_AGENT_URL: http://extraction-agent:8001
      VISION_AGENT_URL: http://vision-agent:8002
      DISCOVERY_AGENT_URL: http://discovery-agent:8004
    depends_on:
      - extraction-agent
      - vision-agent
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  discovery-agent:
    build:
      context: ./services/discovery-agent
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    environment:
      PORT: 8004
      SERVICES_CONFIG: /app/services.json
      LOG_LEVEL: info
      SEARXNG_URL: http://searxng:8888
    volumes:
      - ./services.json:/app/services.json:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Gateway
  agent-gateway:
    build:
      context: ./services/agent-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      SERVICES_CONFIG: /app/services.json
      LOG_LEVEL: info
      EXTRACTION_AGENT_URL: http://extraction-agent:8001
      VISION_AGENT_URL: http://vision-agent:8002
      ORCHESTRATOR_AGENT_URL: http://orchestrator-agent:8003
      DISCOVERY_AGENT_URL: http://discovery-agent:8004
    volumes:
      - ./services.json:/app/services.json:ro
    depends_on:
      - extraction-agent
      - vision-agent
      - orchestrator-agent
      - discovery-agent
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
  ollama_data:

networks:
  default:
    name: mvp-network
