"""LanceDB chunk store — build and query the vector + hybrid index.

Chunks are stored in a Lance table at `state/lancedb/chunks`.
Each chunk record has:
  chunk_id, corpus_id, doc_id, text, section_path, page_start, page_end, keyword_hit

Embeddings are generated by FastEmbed (BAAI/bge-small-en-v1.5).
Hybrid search = vector + BM25 native via LanceDB.

If LanceDB or fastembed is not installed, all public functions raise
LanceStoreUnavailable (a subclass of RuntimeError) so callers can fall back
to BM25-only retrieval without crashing.
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

import pandas as pd

logger = logging.getLogger(__name__)

_LANCE_BASE = Path(__file__).resolve().parents[1] / "state" / "lancedb"
_EMBED_MODEL = "BAAI/bge-small-en-v1.5"


class LanceStoreUnavailable(RuntimeError):
    """Raised when lancedb or fastembed is not installed or a table is missing."""


# ── Lazy singletons ────────────────────────────────────────────────────────────

_embedder: Any = None
_embedder_attempted: bool = False

_db: Any = None
_db_path: str | None = None


def _get_embedder():
    """Lazy singleton. Returns fastembed.TextEmbedding or raises LanceStoreUnavailable."""
    global _embedder, _embedder_attempted
    if _embedder_attempted:
        if _embedder is None:
            raise LanceStoreUnavailable("fastembed is not installed or failed to load")
        return _embedder
    _embedder_attempted = True
    try:
        from fastembed import TextEmbedding  # type: ignore[import]
        _embedder = TextEmbedding(model_name=_EMBED_MODEL)
        logger.info("lance_store: fastembed loaded (%s)", _EMBED_MODEL)
    except ImportError as exc:
        raise LanceStoreUnavailable(f"fastembed not installed: {exc}") from exc
    except Exception as exc:
        raise LanceStoreUnavailable(f"fastembed failed to load: {exc}") from exc
    return _embedder


def _get_db(lance_base: Path | str | None = None):
    """Lazy singleton. Returns lancedb.connect(...) or raises LanceStoreUnavailable."""
    global _db, _db_path
    base = str(lance_base or _LANCE_BASE)
    if _db is not None and _db_path == base:
        return _db
    try:
        import lancedb  # type: ignore[import]
    except ImportError as exc:
        raise LanceStoreUnavailable(f"lancedb not installed: {exc}") from exc
    Path(base).mkdir(parents=True, exist_ok=True)
    try:
        _db = lancedb.connect(base)
        _db_path = base
    except Exception as exc:
        raise LanceStoreUnavailable(f"lancedb connect failed: {exc}") from exc
    return _db


# ── Public API ─────────────────────────────────────────────────────────────────

def build_lance_index(
    chunks_df: pd.DataFrame,
    corpus_id: str,
    *,
    lance_base: Path | str | None = None,
    overwrite: bool = False,
) -> int:
    """Ingest a chunks DataFrame into LanceDB.

    - Generates embeddings in batches of 512 via fastembed.
    - Writes (or appends) to a table named f"chunks_{corpus_id}".
    - Returns number of rows written.
    - If LanceDB/fastembed not available: logs a warning and returns 0.
    """
    if chunks_df.empty:
        return 0

    try:
        embedder = _get_embedder()
        db = _get_db(lance_base)
    except LanceStoreUnavailable as exc:
        logger.warning("lance_store: build_lance_index unavailable (%s)", exc)
        return 0

    table_name = f"chunks_{corpus_id}"
    rows = chunks_df.to_dict("records")

    texts = [str(r.get("text", "")) for r in rows]

    BATCH_SIZE = 512
    all_embeddings: list[list[float]] = []
    for i in range(0, len(texts), BATCH_SIZE):
        batch = texts[i : i + BATCH_SIZE]
        try:
            vecs = list(embedder.embed(batch))
            all_embeddings.extend([list(map(float, v)) for v in vecs])
        except Exception as exc:
            logger.warning("lance_store: embedding batch %d failed (%s)", i // BATCH_SIZE, exc)
            all_embeddings.extend([[0.0] * 384] * len(batch))

    records = []
    for r, vec in zip(rows, all_embeddings):
        records.append(
            {
                "chunk_id": str(r.get("chunk_id", "")),
                "corpus_id": str(r.get("corpus_id", corpus_id)),
                "doc_id": str(r.get("doc_id", "")),
                "text": str(r.get("text", "")),
                "section_path": str(r.get("section_path", "")),
                "page_start": int(r.get("page_start", 0) or 0),
                "page_end": int(r.get("page_end", 0) or 0),
                "keyword_hit": bool(r.get("keyword_hit", False)),
                "vector": vec,
            }
        )

    try:
        existing_tables = db.table_names()
        if table_name in existing_tables and overwrite:
            db.drop_table(table_name)
            db.create_table(table_name, data=records)
        elif table_name in existing_tables:
            tbl = db.open_table(table_name)
            tbl.add(records)
        else:
            db.create_table(table_name, data=records)
        logger.info("lance_store: wrote %d rows to table '%s'", len(records), table_name)
        return len(records)
    except Exception as exc:
        logger.warning("lance_store: write to table '%s' failed (%s)", table_name, exc)
        return 0


def lance_hybrid_search(
    query: str,
    corpus_id: str,
    doc_id: str | None,
    k: int = 20,
    *,
    lance_base: Path | str | None = None,
) -> list[dict]:
    """Hybrid search (vector + BM25) over a corpus's Lance table.

    - Generates query embedding via fastembed.
    - Runs LanceDB hybrid search.
    - If doc_id is set, adds a where clause `doc_id = 'doc_id'`.
    - Returns list of dicts with keys: chunk_id, text, section_path,
      page_start, page_end, doc_id, corpus_id, _distance, keyword_hit.
    - If LanceDB/fastembed not available or table not found: returns [].
    """
    try:
        embedder = _get_embedder()
        db = _get_db(lance_base)
    except LanceStoreUnavailable as exc:
        logger.debug("lance_hybrid_search: unavailable (%s)", exc)
        return []

    table_name = f"chunks_{corpus_id}"
    try:
        if table_name not in db.table_names():
            return []
        tbl = db.open_table(table_name)
    except Exception as exc:
        logger.debug("lance_hybrid_search: open table '%s' failed (%s)", table_name, exc)
        return []

    try:
        vecs = list(embedder.embed([query]))
        query_vec = list(map(float, vecs[0]))
    except Exception as exc:
        logger.debug("lance_hybrid_search: embedding failed (%s)", exc)
        return []

    where_clause = f"doc_id = '{doc_id}'" if doc_id else None

    try:
        search = tbl.search(query_vec, query_type="hybrid").query_str(query)
        if where_clause:
            search = search.where(where_clause)
        results = search.limit(k).to_list()
    except Exception:
        try:
            search = tbl.search(query_vec, query_type="vector")
            if where_clause:
                search = search.where(where_clause)
            results = search.limit(k).to_list()
        except Exception as exc2:
            logger.debug("lance_hybrid_search: search failed (%s)", exc2)
            return []

    if not results:
        return []

    out = []
    for r in results:
        out.append(
            {
                "chunk_id": r.get("chunk_id", ""),
                "text": r.get("text", ""),
                "section_path": r.get("section_path", ""),
                "page_start": r.get("page_start", 0),
                "page_end": r.get("page_end", 0),
                "doc_id": r.get("doc_id", ""),
                "corpus_id": r.get("corpus_id", corpus_id),
                "keyword_hit": r.get("keyword_hit", False),
                "_distance": r.get("_distance", 0.0),
            }
        )
    return out


def corpus_table_exists(corpus_id: str, *, lance_base: Path | str | None = None) -> bool:
    """Return True if f"chunks_{corpus_id}" table exists in LanceDB."""
    try:
        db = _get_db(lance_base)
        return f"chunks_{corpus_id}" in db.table_names()
    except LanceStoreUnavailable:
        return False
    except Exception as exc:
        logger.debug("corpus_table_exists: error (%s)", exc)
        return False


# ── DuckDB document registry (part of the lakehouse) ──────────────────────────

_LAKEHOUSE_DB = Path(__file__).resolve().parents[1] / "state" / "pipeline.duckdb"


def _get_lakehouse_db(db_path: Path | None = None):
    """Get DuckDB connection to the lakehouse."""
    import duckdb
    p = db_path or _LAKEHOUSE_DB
    p.parent.mkdir(parents=True, exist_ok=True)
    con = duckdb.connect(str(p))
    con.execute("""
        CREATE TABLE IF NOT EXISTS doc_registry (
            file_hash       TEXT,
            filing_id       TEXT,
            corpus_id       TEXT,
            entity_name     TEXT DEFAULT '',
            doc_type        TEXT DEFAULT '',
            doc_date        TEXT DEFAULT '',
            chunk_count     INTEGER DEFAULT 0,
            parse_status    TEXT DEFAULT 'OK',
            json_path       TEXT DEFAULT '',
            chunks_indexed  BOOLEAN DEFAULT FALSE,
            lance_indexed   BOOLEAN DEFAULT FALSE,
            registered_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (file_hash, corpus_id)
        )
    """)
    con.execute("""
        CREATE TABLE IF NOT EXISTS corpus_registry (
            corpus_id       TEXT PRIMARY KEY,
            name            TEXT,
            topic           TEXT DEFAULT '',
            doc_count       INTEGER DEFAULT 0,
            chunk_count     INTEGER DEFAULT 0,
            lance_table     TEXT DEFAULT '',
            index_csv_path  TEXT DEFAULT '',
            created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)
    _migrate_corpus_registry_columns(con)
    con.execute("""
        CREATE TABLE IF NOT EXISTS schema_history (
            schema_id       TEXT PRIMARY KEY,
            corpus_id       TEXT,
            schema_version  INTEGER DEFAULT 1,
            columns_json    TEXT DEFAULT '[]',
            approved_at     TIMESTAMP,
            fill_rates_json TEXT DEFAULT '{}'
        )
    """)
    con.execute("""
        CREATE TABLE IF NOT EXISTS extraction_jobs (
            job_id          TEXT PRIMARY KEY,
            corpus_id       TEXT,
            schema_id       TEXT DEFAULT '',
            started_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            completed_at    TIMESTAMP,
            n_docs          INTEGER DEFAULT 0,
            n_rows_extracted INTEGER DEFAULT 0,
            status          TEXT DEFAULT 'running'
        )
    """)
    _ensure_entity_registry_ddl(con)
    _migrate_doc_registry_columns(con)
    return con


def _ensure_entity_registry_ddl(con) -> None:
    """Canonical entity join tables — join authority lives in DuckDB, not the LLM."""
    con.execute("""
        CREATE TABLE IF NOT EXISTS entity_registry (
            entity_id              TEXT PRIMARY KEY,
            cik                    TEXT,
            lei                    TEXT,
            sedar_profile_number   TEXT,
            company_name           TEXT NOT NULL DEFAULT '',
            naics                  TEXT DEFAULT '',
            vault_note_id          TEXT,
            created_at             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at             TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)
    con.execute("""
        CREATE TABLE IF NOT EXISTS entity_identifiers (
            entity_id   TEXT NOT NULL,
            id_type     TEXT NOT NULL,
            id_value    TEXT NOT NULL,
            valid_from  DATE,
            valid_to    DATE,
            source      TEXT DEFAULT '',
            UNIQUE (entity_id, id_type, id_value, valid_from)
        )
    """)
    con.execute("""
        CREATE TABLE IF NOT EXISTS document_registry (
            doc_id       TEXT PRIMARY KEY,
            entity_id    TEXT NOT NULL,
            corpus_id    TEXT NOT NULL,
            doc_type     TEXT DEFAULT '',
            fiscal_year  INTEGER,
            period_end   DATE,
            source_url   TEXT DEFAULT '',
            file_hash    TEXT DEFAULT '',
            profile_number TEXT DEFAULT '',
            indexed_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)
    _migrate_entity_registry_extended(con)
    # Partial unique indexes for external stable keys (DuckDB CREATE UNIQUE INDEX)
    for stmt in (
        "ALTER TABLE entity_registry ADD COLUMN naics TEXT DEFAULT ''",
    ):
        try:
            con.execute(stmt)
        except Exception:
            pass
    for stmt in (
        """CREATE UNIQUE INDEX IF NOT EXISTS idx_entity_registry_cik
           ON entity_registry(cik) WHERE cik IS NOT NULL AND cik != ''""",
        """CREATE UNIQUE INDEX IF NOT EXISTS idx_entity_registry_lei
           ON entity_registry(lei) WHERE lei IS NOT NULL AND lei != ''""",
        """CREATE UNIQUE INDEX IF NOT EXISTS idx_entity_registry_sedar
           ON entity_registry(sedar_profile_number)
           WHERE sedar_profile_number IS NOT NULL AND sedar_profile_number != ''""",
        """CREATE INDEX IF NOT EXISTS idx_entity_identifiers_lookup
           ON entity_identifiers(id_type, id_value)""",
    ):
        try:
            con.execute(stmt)
        except Exception as exc:
            logger.debug("entity registry index (may exist): %s", exc)


def _migrate_entity_registry_extended(con) -> None:
    """Add columns for master_sedar_issuers01_enriched layout and document_registry.profile_number."""
    for sql in (
        "ALTER TABLE entity_registry ADD COLUMN sedar_name TEXT",
        "ALTER TABLE entity_registry ADD COLUMN legal_name_en TEXT",
        "ALTER TABLE entity_registry ADD COLUMN issuer_type TEXT",
        "ALTER TABLE entity_registry ADD COLUMN principal_jurisdiction TEXT",
        "ALTER TABLE entity_registry ADD COLUMN profile_id TEXT",
        "ALTER TABLE entity_registry ADD COLUMN website TEXT",
        "ALTER TABLE entity_registry ADD COLUMN size TEXT",
        "ALTER TABLE entity_registry ADD COLUMN financial_year_end TEXT",
        "ALTER TABLE entity_registry ADD COLUMN has_secondary_key BOOLEAN",
        "ALTER TABLE document_registry ADD COLUMN profile_number TEXT DEFAULT ''",
    ):
        try:
            con.execute(sql)
        except Exception:
            pass


def _migrate_corpus_registry_columns(con) -> None:
    """Federated catalog: each corpus is a row; Lance table name + paths link vector search to metadata."""
    for sql in (
        "ALTER TABLE corpus_registry ADD COLUMN docs_dir TEXT DEFAULT ''",
        "ALTER TABLE corpus_registry ADD COLUMN chunks_parquet_path TEXT DEFAULT ''",
        "ALTER TABLE corpus_registry ADD COLUMN source_kind TEXT DEFAULT ''",
        "ALTER TABLE corpus_registry ADD COLUMN lance_chunk_rows INTEGER DEFAULT 0",
    ):
        try:
            con.execute(sql)
        except Exception:
            pass


def _migrate_doc_registry_columns(con) -> None:
    """Add entity / period columns to doc_registry if missing."""
    for sql in (
        "ALTER TABLE doc_registry ADD COLUMN entity_id TEXT DEFAULT ''",
        "ALTER TABLE doc_registry ADD COLUMN fiscal_year INTEGER",
        "ALTER TABLE doc_registry ADD COLUMN period_end DATE",
    ):
        try:
            con.execute(sql)
        except Exception:
            pass  # column already exists


def register_doc_in_lakehouse(
    filing_id: str,
    corpus_id: str,
    *,
    file_hash: str = "",
    entity_name: str = "",
    doc_type: str = "",
    doc_date: str = "",
    chunk_count: int = 0,
    parse_status: str = "OK",
    json_path: str = "",
    entity_id: str = "",
    fiscal_year: int | None = None,
    period_end: str | None = None,
    profile_number: str = "",
    db_path: Path | None = None,
) -> None:
    """Register a parsed document in the DuckDB lakehouse registry.

    Safe to call multiple times — uses INSERT OR REPLACE.
    """
    try:
        con = _get_lakehouse_db(db_path)
        con.execute(
            "DELETE FROM doc_registry WHERE filing_id = ? AND corpus_id = ?",
            [filing_id, corpus_id],
        )
        con.execute("""
            INSERT INTO doc_registry
            (file_hash, filing_id, corpus_id, entity_name, doc_type, doc_date,
             chunk_count, parse_status, json_path, entity_id, fiscal_year, period_end,
             registered_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, now())
        """, [
            file_hash, filing_id, corpus_id, entity_name, doc_type, doc_date,
            chunk_count, parse_status, json_path, entity_id or "",
            fiscal_year, period_end,
        ])
        if filing_id and entity_id and corpus_id:
            try:
                fy = int(fiscal_year) if fiscal_year is not None else None
            except (TypeError, ValueError):
                fy = None
            ped = None
            if period_end:
                try:
                    ped = period_end
                except Exception:
                    ped = None
            pn = (profile_number or "").strip()
            con.execute("""
                INSERT INTO document_registry
                (doc_id, entity_id, corpus_id, doc_type, fiscal_year, period_end,
                 file_hash, profile_number, indexed_at)
                VALUES (?, ?, ?, ?, ?, CAST(? AS DATE), ?, ?, now())
                ON CONFLICT(doc_id) DO UPDATE SET
                    entity_id = excluded.entity_id,
                    corpus_id = excluded.corpus_id,
                    doc_type = excluded.doc_type,
                    fiscal_year = excluded.fiscal_year,
                    period_end = excluded.period_end,
                    file_hash = excluded.file_hash,
                    profile_number = excluded.profile_number,
                    indexed_at = now()
            """, [filing_id, entity_id, corpus_id, doc_type or "", fy, ped or None, file_hash or "", pn])
        con.close()
    except Exception as exc:
        logger.warning("register_doc_in_lakehouse failed: %s", exc)


def upsert_corpus_registry(
    corpus_id: str,
    name: str,
    *,
    topic: str = "",
    doc_count: int = 0,
    chunk_count: int = 0,
    index_csv_path: str = "",
    docs_dir: str = "",
    chunks_parquet_path: str = "",
    source_kind: str = "",
    lance_chunk_rows: int = 0,
    db_path: Path | None = None,
) -> None:
    """Register or update a corpus in the federated catalog (DuckDB).

    This is the cross-corpus metadata graph row: index CSV path, PDF root,
    chunks parquet path, and the LanceDB table name (``chunks_<corpus_id>``)
    used by :func:`lance_hybrid_search`. Not a single global "filings index" —
    each upload / corpus gets its own row.
    """
    try:
        con = _get_lakehouse_db(db_path)
        lance_table = f"chunks_{corpus_id}"
        con.execute("""
            INSERT INTO corpus_registry
            (corpus_id, name, topic, doc_count, chunk_count, lance_table, index_csv_path,
             docs_dir, chunks_parquet_path, source_kind, lance_chunk_rows, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, now())
            ON CONFLICT(corpus_id) DO UPDATE SET
                name = excluded.name,
                topic = excluded.topic,
                doc_count = excluded.doc_count,
                chunk_count = excluded.chunk_count,
                lance_table = excluded.lance_table,
                index_csv_path = excluded.index_csv_path,
                docs_dir = excluded.docs_dir,
                chunks_parquet_path = excluded.chunks_parquet_path,
                source_kind = excluded.source_kind,
                lance_chunk_rows = excluded.lance_chunk_rows,
                updated_at = now()
        """, [
            corpus_id, name, topic, doc_count, chunk_count, lance_table, index_csv_path,
            docs_dir or "", chunks_parquet_path or "", source_kind or "", int(lance_chunk_rows or 0),
        ])
        con.close()
    except Exception as exc:
        logger.warning("upsert_corpus_registry failed: %s", exc)


def get_corpus_catalog_row(corpus_id: str, *, db_path: Path | None = None) -> dict[str, Any] | None:
    """Return catalog metadata for one corpus (paths + Lance table name)."""
    try:
        con = _get_lakehouse_db(db_path)
        row = con.execute(
            """
            SELECT corpus_id, name, topic, doc_count, chunk_count, lance_table, index_csv_path,
                   docs_dir, chunks_parquet_path, source_kind, lance_chunk_rows
            FROM corpus_registry WHERE corpus_id = ?
            """,
            [corpus_id],
        ).fetchone()
        con.close()
        if not row:
            return None
        keys = (
            "corpus_id", "name", "topic", "doc_count", "chunk_count", "lance_table",
            "index_csv_path", "docs_dir", "chunks_parquet_path", "source_kind", "lance_chunk_rows",
        )
        return dict(zip(keys, row))
    except Exception as exc:
        logger.debug("get_corpus_catalog_row: %s", exc)
        return None


def lance_table_name_for_corpus(corpus_id: str) -> str:
    """Canonical Lance table name; matches :func:`build_lance_index` / hybrid search."""
    return f"chunks_{corpus_id}"


def get_lakehouse_stats(*, db_path: Path | None = None) -> dict:
    """Return lakehouse statistics across all corpora."""
    try:
        con = _get_lakehouse_db(db_path)
        stats = {}

        row = con.execute("""
            SELECT COUNT(DISTINCT corpus_id) as n_corpora,
                   COUNT(*) as n_docs,
                   SUM(chunk_count) as n_chunks
            FROM doc_registry WHERE parse_status LIKE 'OK%'
        """).fetchone()
        stats["n_corpora"] = row[0] if row else 0
        stats["n_docs"] = row[1] if row else 0
        stats["n_chunks"] = row[2] if row else 0

        corpora = con.execute(
            """
            SELECT corpus_id, name, doc_count, chunk_count, lance_table, index_csv_path,
                   docs_dir, chunks_parquet_path, source_kind, lance_chunk_rows
            FROM corpus_registry ORDER BY updated_at DESC LIMIT 20
            """
        ).fetchall()
        stats["corpora"] = [
            {
                "corpus_id": r[0],
                "name": r[1],
                "doc_count": r[2],
                "chunk_count": r[3],
                "lance_table": r[4],
                "index_csv_path": r[5],
                "docs_dir": r[6],
                "chunks_parquet_path": r[7],
                "source_kind": r[8],
                "lance_chunk_rows": r[9],
            }
            for r in corpora
        ]

        con.close()
        return stats
    except Exception:
        return {"n_corpora": 0, "n_docs": 0, "n_chunks": 0, "corpora": []}
